###
@URL=http://localhost:3002/api

###
GET {{URL}}/blogs

###

POST {{URL}}/blogs
Content-Type: application/json

{
  "author": "Davey jones",
  "url": "http://pirates.com"
}

###
DELETE {{URL}}/blogs/27

###
PUT {{URL}}/blogs/2
Content-Type: application/json

{
  "likes": 3
}

###

GET {{URL}}/users

###

POST {{URL}}/users
Content-Type: application/json

{
  "username": "testuser3",
  "name": "Mike"
}