###
@URL=http://localhost:3002/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyNEBnbWFpbC5jb20iLCJpZCI6NCwiaWF0IjoxNjY1NzY2MTM3fQ.YrH6RVzApWRCqSOzoDTnWko28SGVMb8rgYk-XLHctrs

###
GET {{URL}}/blogs

###
GET {{URL}}/blogs?search=jones

###

POST {{URL}}/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMUBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjY2MDQwMDEzfQ.YKcbCEND_cZ3-Tr6pFFpVtDkrZSxgqp7Pk7no-eWX_k
Content-Type: application/json

{
  "title": "Star Wars 2",
  "author": "Qui-Gon",
  "url": "http://starwars.com",
  "likes": 12
}

###
DELETE {{URL}}/blogs/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyNEBnbWFpbC5jb20iLCJpZCI6NCwiaWF0IjoxNjY1NzY2NzM4fQ.ws9AvRjj0hIIp99pJRrNoXobzGfnnhm2gJXE8xP2QRE

###
PUT {{URL}}/blogs/2
Content-Type: application/json

{
  "likes": 3
}

###

GET {{URL}}/users

###

POST {{URL}}/users
Content-Type: application/json

{
  "username": "testuser2@gmail.com",
  "name": "Test User 2"
}

###

POST {{URL}}/login
Content-Type: application/json

{
  "username": "testuser2@gmail.com",
  "password": "secret"
}


###
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyNEBnbWFpbC5jb20iLCJpZCI6NCwiaWF0IjoxNjY1NzY1NDYwfQ.aoxQGI1tZHONtJg_hECvhUogg3S4KMh-dPpyOkQ5LZs",
  "username": "testuser4@gmail.com",
  "name": "Test User 4"
}

###
POST {{URL}}/readinglists
Content-Type: application/json

{
  "userId": 2,
  "blogId": 5
}

###

PUT {{URL}}/readinglists/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMkBnbWFpbC5jb20iLCJpZCI6MiwiaWF0IjoxNjY2MDQ5MTQ0fQ.lW1aJfbYzTSmczAF9AQGI20WITEi417iPxEC19yAQ8o

{
  "read": 3
}